service: kevin-pomelo-test

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1 # else it would be us-east-1

  # IAM role if any
  # iam: ...

  # VPC configuration if any
  # vpc: ...

package:
  individually: true

plugins:
  - serverless-offline

functions:
  # API Functions
  ## Transaction service
  create-transaction:
    handler: src/services/transactions/index.createTransactionHandler
    events:
      - httpApi:
          method: POST # Indicated clearly only accept POST method
          path: /transaction
  retrieve-transactions:
    handler: src/services/transactions/index.retrieveTransactionsHandler
    events:
      - httpApi:
          method: GET # Indicated clearly only accept GET method
          path: /transactions
  update-transaction-status:
    handler: src/services/transactions/index.updateTransactionStatusHandler
    events:
      - httpApi:
          method: PATCH # Indicated clearly only accept PATCH method
          path: /transaction/{transactionId}
